# ~/.config/starship.toml

# Use custom format
format = "$time [\\[](bold #b8bb26)$username$directory[\\]](bold #b8bb26)$git_branch$git_status[\\$](dimmed) "

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the newline at the start of the prompt
add_newline = false

[time]
time_format = "%I:%M %p"
format = "[$time]($style)"
style = "#ebdbb2"
disabled = false
use_12hr = true

[username]
format = "[$user]($style) [in ](dimmed)"
style_user = "bold #fb4934"
show_always = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
truncation_length = 1
style = "bold #fabd2f"

[git_branch]
format = " [$symbol$branch]($style) "
style = "bold #d3869b"
